### ISSUE TITLE
To-night

### ISSUE THREAD

**Issue by zikalify** [standardebooks/robert-frost_north-of-boston#1]
This (https://github.com/standardebooks/robert-frost_north-of-boston/blob/master/src/epub/text/north-of-boston.xhtml) has several instances of the word 'to-night', according to the website though it says that sort of this would be changed to be more modern and therefore should be 'tonight' right? Or were these intentionally left as 'to-night'?

**Comment by acabal** [comment]
Hi there, you're correct, we typically remove hyphens from words like "to-night"... _except for poetry_, where we explicitly leave them as-is, since they may affect how a poem scans.
